### PR TITLE
update GeoLite2 sha

### PR DESCRIPTION
**Pull request by jsvd**
Thanks for contributing to Logstash! If you haven't already signed our CLA, here's a handy link: https://www.elastic.co/contributor-agreement/

### CODE REVIEW

**Comment by jordansissel** [comment]
Geoip data test failing due to some precision changes (City "Worcester" now reported from the test IP being "Salem")

**Comment by jordansissel** [comment]
Otherwise LGTM.

**Comment by yaauie** [comment]
I have validated that the file currently being returned from the listed URI has that sha1; do we have any external validation from the provider that it _should_ be that sha1? I see that they list other files with their MD5's, but don't see a checksum of any kind on their site for this particular URI.

**Comment by jsvd** [comment]
There isn't, I checked the md5 and then computed sha1.

**Pull request merged**
