### PR TITLE
This check for Thread.current is more portable across JRuby versions

### PR DESCRIPTION
**Pull request by andrewvc**

### CODE REVIEW

**Comment by ph** [comment]
Same failures  you have to change the test too?

Have you tested on Jruby 1.7.2x ?
```
Failures:

  1) LogStash::Filters::GeoIP re-initializing thread current DB should initialize the DB on lookup, regardless of thread state
     Failure/Error: Thread.current.thread_variables.delete plugin.threadkey
     NoMethodError:
       undefined method `thread_variables' for #<Thread:0x6831d8fd run>
     # ./spec/filters/geoip_spec.rb:258:in `(root)'

**Comment by jordansissel** [comment]
Thread.current.key? works for me in JRuby 1.7.19  - what does this change fix?

**Comment by andrewvc** [comment]
@jordansissel Apparently `Thread.current.thread_variables.delete` doesn't work on some rubies. I meant to switch the test to just set the value to nil, which meant I couldn't use `key?`

**Comment by andrewvc** [comment]
Ok, pushed new test code that should fix all this weirdness.

**Comment by jordansissel** [comment]
@andrewvc ahh ok that makes sense.

**Comment by andrewvc** [comment]
@jordansissel it's hard to push the right code when the error isn't happening on your own box. Apologies for the confusion :)

**Comment by ph** [comment]
@andrewvc LGTM, test passes.

**Pull request closed without merging**
